### ISSUE TITLE
compatible of ag-grid with angular 2.4.3 version

### ISSUE THREAD

**Issue by usersk12** [ceolter/ag-grid-ng2-example#36]
HI, 

Thanks for your continuous support. 
We are planning to use the latest version of angular 2.4.3 version. 
We need to confirm that is ag-grid support has been added with angular2.4.3 version or not?

**Comment by yuntaoguo** [comment]
Hi, 

During  first running the example. The license of ag-grid invalid. Some solution for that please?

**Comment by seanlandsman** [comment]
Yes, it'll work fine with all 2.4.x versions

**Comment by usersk12** [comment]
Thanks for sharing the information. It is working fine on this version.

**Comment by sandeep2701kumar** [comment]
I am using angular version 7.2.2 and typescript version 3.2.2. I am getting this error:  in node_modules/ag-grid-community/dist/lib/interfaces/iAgChartOptions.d.ts(28,14): error TS2304: Cannot find name 'Omit'. Please let me know what should i do.
